package enums;

public enum EffectTyps {
   AND,OR,ASSET_FROM_RESERVE,GAIN_CONDITION,LOOSE, RANDOM_ASSET, BECOME_DELAYED, NULL, GAIN, GAIN_CLUE, ADVANCE_DOOM, NEXT_INVESTIGATOR, SPAWN_CLUE, MOVE, IMPROVE, RETREAT_DOOM, RETREAT_OMEN, ADVANCE_OMEN, RANDOM_ARTIFACT, SPEND
}
