package enums;

public enum EffectTyps {
   AND,OR,ASSET_FROM_RESERVE,GAIN_CONDITION, LOOSE_OR_GAIN_HEALTH_SANITY, RANDOM_ASSET, BECOME_DELAYED, NULL, GAIN, GAIN_CLUE, ADVANCE_DOOM, NEXT_INVESTIGATOR, SPAWN_CLUE, MOVE, IMPROVE, RETREAT_DOOM, RETREAT_OMEN, ADVANCE_OMEN, RANDOM_ARTIFACT, SWITCH_PHASE, MONSTER_SURGE, SPAWN_GATE, SPAWN_MONSTER, RECKONING, GAIN_FOCUS, GAIN_TICKET, TRADE, CLOSE_GATE, DISCARD, CHANGE_MONSTER_ATTRIBUTE, TEMPORARY_SKILL_BONUS, CUSTOM, SPEND
}
