package enums;

public enum EncounterType {
   COMBAT_ENCOUNTER,STANDARD_ENCOUNTER, RESEARCH_ENCOUNTER, EUROPE_ENCOUNTER, AMERICA_ENCOUNTER, ASIA_ENCOUNTER, EXPEDITION_ENCOUNTER, OTHER_WORLD_ENCOUNTER, SPECIAL_ENCOUNTER, RUMOR_ENCOUNTER;
}
